# Generated by Django 3.2.5 on 2021-09-08 22:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=15)),
                ('zip_code', models.IntegerField()),
                ('pickup_day', models.CharField(max_length=9)),
                ('has_extra_pickup', models.BooleanField(default=False)),
                ('extra_pickup_day', models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_start', models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('suspension_end', models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
